name: myntra
channels:
  - https://conda.anaconda.org/menpo
  - conda-forge
dependencies:
- appnope=0.1.0
- blas=1.1
- bleach=1.5.0
- ca-certificates=2016.9.26
- certifi=2016.9.26
- cffi=1.7.0
- click=6.6
- cryptography=1.7.1
- cycler=0.10.0
- decorator=4.0.11
- entrypoints=0.2.2
- eventlet=0.19.0
- ffmpeg=2.7.0
- flask=0.11.1
- flask-socketio=2.7.1
- freeimage=3.17.0
- freetype=2.6.3
- greenlet=0.4.11
- h5py=2.6.0
- hdf5=1.8.17
- html5lib=0.999
- icu=54.1
- idna=2.1
- imageio=1.5.0
- ipykernel=4.5.2
- ipython=5.1.0
- ipython_genutils=0.1.0
- ipywidgets=5.1.5
- itsdangerous=0.24
- jinja2=2.8
- jpeg=9b
- jsonschema=2.5.1
- jupyter=1.0.0
- jupyter_client=4.4.0
- jupyter_console=5.0.0
- jupyter_core=4.2.1
- libffi=3.2.1
- libgfortran=3.0.0
- libpng=1.6.28
- libsodium=1.0.10
- libtiff=4.0.6
- markupsafe=0.23
- matplotlib=2.0.0
- mistune=0.7.3
- nbconvert=5.1.1
- nbformat=4.2.0
- ncurses=5.9
- networkx=1.11
- notebook=4.3.1
- numpy=1.11.3
- openblas=0.2.19
- opencv3=3.1.0
- openssl=1.0.2h
- pandas=0.19.2
- pandoc=1.19.1
- pandocfilters=1.4.1
- patsy=0.4.1
- pexpect=4.2.1
- pickleshare=0.7.3
- pillow=4.0.0
- pip=9.0.1
- prompt_toolkit=1.0.9
- ptyprocess=0.5.1
- pyasn1=0.1.9
- pycparser=2.17
- pygments=2.2.0
- pyopenssl=16.0.0
- pyparsing=2.1.10
- pyqt=5.6.0
- python=3.5.2
- python-dateutil=2.6.0
- python-engineio=1.0.0
- python-socketio=1.5.1
- pytz=2016.10
- pyzmq=16.0.2
- qt=5.6.2
- qtconsole=4.2.1
- readline=6.2
- requests=2.12.4
- scikit-image=0.12.3
- scikit-learn=0.18
- scipy=0.18.1
- seaborn=0.7.1
- setuptools=33.1.0
- simplegeneric=0.8.1
- sip=4.18
- six=1.10.0
- sqlite=3.13.0
- statsmodels=0.6.1
- tbb=4.3_20141023
- terminado=0.6
- testpath=0.3
- tk=8.5.19
- tornado=4.4.2
- traitlets=4.3.1
- wcwidth=0.1.7
- werkzeug=0.11.10
- wheel=0.29.0
- widgetsnbextension=1.2.3
- xz=5.2.2
- zeromq=4.1.5
- zlib=1.2.11
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - keras==1.2.1
  - moviepy==0.2.2.11
  - prompt-toolkit==1.0.9
  - protobuf==3.1.0.post1
  - pyyaml==3.12
  - tensorflow==0.12.1
  - theano==0.8.2
  - tqdm==4.11.2
